	reloj_soc u0 (
		.audio_BCLK                         (<connected-to-audio_BCLK>),                         //                   audio.BCLK
		.audio_DACDAT                       (<connected-to-audio_DACDAT>),                       //                        .DACDAT
		.audio_DACLRCK                      (<connected-to-audio_DACLRCK>),                      //                        .DACLRCK
		.audio_config_SDAT                  (<connected-to-audio_config_SDAT>),                  //            audio_config.SDAT
		.audio_config_SCLK                  (<connected-to-audio_config_SCLK>),                  //                        .SCLK
		.audio_pll_clk                      (<connected-to-audio_pll_clk>),                      //               audio_pll.clk
		.buttons_export                     (<connected-to-buttons_export>),                     //                 buttons.export
		.clk_clk                            (<connected-to-clk_clk>),                            //                     clk.clk
		.hps_f2h_cold_reset_req_reset_n     (<connected-to-hps_f2h_cold_reset_req_reset_n>),     //  hps_f2h_cold_reset_req.reset_n
		.hps_f2h_debug_reset_req_reset_n    (<connected-to-hps_f2h_debug_reset_req_reset_n>),    // hps_f2h_debug_reset_req.reset_n
		.hps_f2h_stm_hw_events_stm_hwevents (<connected-to-hps_f2h_stm_hw_events_stm_hwevents>), //   hps_f2h_stm_hw_events.stm_hwevents
		.hps_f2h_warm_reset_req_reset_n     (<connected-to-hps_f2h_warm_reset_req_reset_n>),     //  hps_f2h_warm_reset_req.reset_n
		.hps_h2f_reset_reset_n              (<connected-to-hps_h2f_reset_reset_n>),              //           hps_h2f_reset.reset_n
		.hps_io_hps_io_sdio_inst_CMD        (<connected-to-hps_io_hps_io_sdio_inst_CMD>),        //                  hps_io.hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_PWREN      (<connected-to-hps_io_hps_io_sdio_inst_PWREN>),      //                        .hps_io_sdio_inst_PWREN
		.hps_io_hps_io_sdio_inst_D0         (<connected-to-hps_io_hps_io_sdio_inst_D0>),         //                        .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1         (<connected-to-hps_io_hps_io_sdio_inst_D1>),         //                        .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK        (<connected-to-hps_io_hps_io_sdio_inst_CLK>),        //                        .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2         (<connected-to-hps_io_hps_io_sdio_inst_D2>),         //                        .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3         (<connected-to-hps_io_hps_io_sdio_inst_D3>),         //                        .hps_io_sdio_inst_D3
		.hps_io_hps_io_uart0_inst_RX        (<connected-to-hps_io_hps_io_uart0_inst_RX>),        //                        .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX        (<connected-to-hps_io_hps_io_uart0_inst_TX>),        //                        .hps_io_uart0_inst_TX
		.hps_io_hps_io_uart0_inst_CTS       (<connected-to-hps_io_hps_io_uart0_inst_CTS>),       //                        .hps_io_uart0_inst_CTS
		.hps_io_hps_io_uart0_inst_RTS       (<connected-to-hps_io_hps_io_uart0_inst_RTS>),       //                        .hps_io_uart0_inst_RTS
		.leds_export                        (<connected-to-leds_export>),                        //                    leds.export
		.memory_mem_a                       (<connected-to-memory_mem_a>),                       //                  memory.mem_a
		.memory_mem_ba                      (<connected-to-memory_mem_ba>),                      //                        .mem_ba
		.memory_mem_ck                      (<connected-to-memory_mem_ck>),                      //                        .mem_ck
		.memory_mem_ck_n                    (<connected-to-memory_mem_ck_n>),                    //                        .mem_ck_n
		.memory_mem_cke                     (<connected-to-memory_mem_cke>),                     //                        .mem_cke
		.memory_mem_cs_n                    (<connected-to-memory_mem_cs_n>),                    //                        .mem_cs_n
		.memory_mem_ras_n                   (<connected-to-memory_mem_ras_n>),                   //                        .mem_ras_n
		.memory_mem_cas_n                   (<connected-to-memory_mem_cas_n>),                   //                        .mem_cas_n
		.memory_mem_we_n                    (<connected-to-memory_mem_we_n>),                    //                        .mem_we_n
		.memory_mem_reset_n                 (<connected-to-memory_mem_reset_n>),                 //                        .mem_reset_n
		.memory_mem_dq                      (<connected-to-memory_mem_dq>),                      //                        .mem_dq
		.memory_mem_dqs                     (<connected-to-memory_mem_dqs>),                     //                        .mem_dqs
		.memory_mem_dqs_n                   (<connected-to-memory_mem_dqs_n>),                   //                        .mem_dqs_n
		.memory_mem_odt                     (<connected-to-memory_mem_odt>),                     //                        .mem_odt
		.memory_mem_dm                      (<connected-to-memory_mem_dm>),                      //                        .mem_dm
		.memory_oct_rzqin                   (<connected-to-memory_oct_rzqin>),                   //                        .oct_rzqin
		.resetxd_reset_n                    (<connected-to-resetxd_reset_n>)                     //                 resetxd.reset_n
	);

